### ISSUE TITLE
Affine transformations

### ISSUE THREAD

**Issue by wgreenr** [GiovineItalia/Compose.jl#115]
Could you please suggest whether 2D transformations (like rotations, skews, translations) are available, and if so how to use them? There was no example in docs, just polygons/rectangles/ellipses rendering.

**Comment by shashi** [comment]
`rotation` and `mirror` is available, and can be passed in as key word arguments to context.

See
http://nbviewer.ipython.org/github/shashi/ijulia-notebooks/blob/master/funcgeo/Functional%20Geometry.ipynb#Implementing-the-primitives-with-Compose for examples.

the basic API is `compose(context(rotation=Rotation(...), mirror=Mirror(...)), <form>)`. translation can be implemented by changing the boundaries of your context. I am not sure how skew can be implemented though.
