### ISSUE TITLE
require deprecation warning

### ISSUE THREAD

**Issue by xxfelixxx** [GiovineItalia/Compose.jl#151]
Running julia 0.4.0:

Version 0.4.0-pre (2015-09-03 23:23 UTC)
Commit bcb2858 (7 days old master)
x86_64-redhat-linux

When I do:
julia> using Gadfly
it recompiles lots of packages, and also throws this warning:

WARNING: `require` is deprecated, use `using` or `import` instead
 in depwarn at deprecated.jl:73
 in require at deprecated.jl:663
 in isinstalled at /home/felix/.julia/v0.4/Compose/src/Compose.jl:34
 in isinstalled at /home/felix/.julia/v0.4/Compose/src/Compose.jl:28
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
 in anonymous at no file:2
 in process_options at ./client.jl:284
 in _start at ./client.jl:411

I would submit a change for this, but since I am new to Julia, I do not know what the right 'fix' would be?

**Comment by bjarthur** [comment]
please reopen if this is still relevant
