### ISSUE TITLE
simple example in docs?

### ISSUE THREAD

**Issue by mkborregaard** [GiovineItalia/Compose.jl#154]
Hi, 
I wanted to learn Compose but find it very difficult, because it seems to require a certain mindset that I cannot attune to.  Might it be possible to come with an example that just illustrated how one would draw a simple drawing with some different elements. I did go through all the examples, but they seem to be more tuned to illustrating special cases where compose excels, rather than showing (at least to me) how to use it as a general-purpose drawing tool. (I am trying to draw a phylogeny, which essentially consists of a _lot_ of line segments drawn individually). Thanks

**Comment by cuv2** [comment]
Hi,

I had the same difficulties and wrote the following for multiple line segments:


using Compose
using Colors
Compose.set_default_graphic_size(1inch, 1inch)

#Method 1

points = fill(Array((Float64,Float64),2),2)
points[1] = [(0,0),(1,1)]
points [2]= [(0,0.5),(0.5,1)]
compose(context(), line(points),  stroke(colorant"tomato") ,linewidth(1))

#Method 2

points = [[[x] for x = ([(0.0,0.0),(1,1)],[(0,0.5),(0.5,1)])]]
compose(context(), line(points),  stroke(colorant"tomato") ,linewidth(1))


The point is, I guess, to make vectors of points.
Hope this help.

Alain

**Comment by mkborregaard** [comment]
Thanks a lot – it looks like just what I am looking for. I cannot completely figure out how to build the vectors though – the method seems to throw an exception:

```
fill(Array((Float64,Float64),2),2)
ERROR: MethodError: `convert` has no method matching convert(::Type{Array{T,N}}, ::Tuple{DataType,DataType}, ::Int64)
This may have arisen from a call to the constructor Array{T,N}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  Array{T}(::Type{T}, ::Integer)
  Array{T}(::Type{T}, ::Integer, ::Integer)
  Array{T}(::Type{T}, ::Integer, ::Integer, ::Integer)
  ...
 in call at essentials.jl:58
```

Best,
Michael

**Comment by cuv2** [comment]
For me it works well on Juliabox with the Julia 0.3.11 Kernel 

Alain

**Comment by mkborregaard** [comment]
The issue may be I'm on 0.4. The structure you are building is a 1D array of 1D arrays of 2-element long Float64 tuples?

**Comment by cuv2** [comment]
yes, this is exactly this structure.
You can show it with:

println(typeof(points))

**Comment by mkborregaard** [comment]
Thanks. So if I have 4 Vectors: x1, x2, y1, y2 I can get the right structure with 

points = [[(x1[i], y1[i]), (x2[i], y2[i])] for i in 1:length(x1)]

Thanks a lot, this is immensely helpful! I will leave the issue open as I still think it would be a nice feature

**Comment by cuv2** [comment]
Here is an other method, I would say far better than the previous ones (because it seems to be at the heart of Compose's design):

```
point = [(0, 0), (1, 1)]
point2 = [(0,0.5),(0.5,1)]

c = compose(context(), line(point2),  stroke(colorant"tomato") ,linewidth(1))
compose(context(), line(point),  stroke(colorant"tomato") ,linewidth(1), c)
```

**Comment by mkborregaard** [comment]
Thanks a lot! I don't think that is better, though - in my experience compose is much faster at drawing lines from arrays, whereas multiple nested composes take a lot of time. This may be due to all the warnings it has to print, though!
Also, doing this for many lines will create multiple nested groupings, which will make post-processing in a vector editor such as illustrator much more difficult.

**Comment by Mattriks** [comment]
See examples in the new [Forms gallery](http://giovineitalia.github.io/Compose.jl/latest/gallery/forms.html)

**Comment by mkborregaard** [comment]
Great, that's exactly what I wanted.
