### ISSUE TITLE
'absolue' in property.jl line 389

### ISSUE THREAD

**Issue by mkborregaard** [GiovineItalia/Compose.jl#155]
Must be a typo in the code.

Also - is there a forum to get help for compose? I am trying to find out 1) how to draw an arc, and 2) how to make text italic.

Thanks,
M

**Comment by Mattriks** [comment]
1) See the new Forms gallery: [arc](http://giovineitalia.github.io/Compose.jl/latest/gallery/forms.html#[arc](@ref)-1) and [slice](http://giovineitalia.github.io/Compose.jl/latest/gallery/forms.html#[slice](@ref)-1)
2) see the links in the [Text](http://giovineitalia.github.io/Compose.jl/latest/tutorial.html#Text-1)  section of the docs, but Julia also supports [Unicode](https://docs.julialang.org/en/v1/manual/unicode-input/#Unicode-Input-1)

**Comment by mkborregaard** [comment]
awesome :heart:
