### ISSUE TITLE
opacity and alpha in pdf and png output

### ISSUE THREAD

**Issue by dgleich** [GiovineItalia/Compose.jl#181]
The current pdf output does not seem to support opacity or alpha values. I'm guessing this is due to the Cairo PDF surface version not being high enough? I didn't see a quick way of fixing this though.

Here's a minimal example

```
using Compose
fig = compose(context(), 
        (context(0.0, 0.0, 0.5, 0.5), circle(), fill("tomato")),
(context(0.5, 0.5, 0.5, 0.5), circle(), fill("tomato"), fillopacity(0.25)))
img = PDF("test-opacity-alpha.pdf",100mm,100mm)
draw(img,fig)
imgpng = PNG("test-opacity-alpha.png",100mm,100mm)
draw(imgpng,fig)
```

The SVG file produced in jupyter looks fine though.

**Comment by dgleich** [comment]
My current workaround is to save as an svg and then use inkscape to convert the svg to a pdf, which looks great.

**Comment by lobingera** [comment]
CairoPDF surface supports transparency and png for sure. I changed one of the cairo examples (https://github.com/JuliaLang/Cairo.jl/blob/master/samples/sample_arc.jl) to draw to PDF and got this:

![snapshot6](https://cloud.githubusercontent.com/assets/5199059/12222875/5b4df0ea-b7c8-11e5-81b9-a7ea4c099513.png)

(the red lines are 0.6 transparent).
Looks like the information an element has x opacity is not correctly forwarded to the draw methods.

**Comment by dgleich** [comment]
Ah, great point! I had thought that Compose was using Cairo for the SVG output too because there is an SVG backend defined. But it seems the SVG output uses a different path. 

Using Cairo for SVG also shows the issue.

~~~
CairoSVG = Compose.Image{Compose.SVGBackend}
imgsvg2 = CairoSVG("test-opacity-cario.svg", 100mm, 100mm)
draw(imgsvg2, fig)
~~~

whereas the standard SVG output does not

~~~
imgsvg = SVG("test-opacity-alpha.svg", 100mm, 100mm)
draw(imgsvg, fig)
~~~

**Comment by dgleich** [comment]
Okay, new possible cause.

It looks like these functions may not nest well...

~~~
function apply_property(img::Image, p::StrokePrimitive)
    img.stroke = p.color
end


function apply_property(img::Image, p::FillPrimitive)
    img.fill = p.color
end


function apply_property(img::Image, p::FillOpacityPrimitive)
    img.fill = RGBA{Float64}(color(img.fill), p.value)
end


function apply_property(img::Image, p::StrokeOpacityPrimitive)
    img.stroke = RGBA{Float64}(color(img.stroke), p.value)
end
~~~

So if you set the fill-opacity, and then set the color, one of the two will get overridden.

And we can verify this by seeing that the following example works

~~~
using Compose
fig = compose(context(), 
        (context(0.0, 0.0, 0.5, 0.5), circle(), fill(RGBA{Float64}(0.8,0.,0.,1))),
(context(0.5, 0.5, 0.5, 0.5), circle(), fill(RGBA{Float64}(0.8,0.,0.,0.25))))
img = PDF("test-opacity-fill.pdf",100mm,100mm)
draw(img,fig)
~~~

**Comment by lobingera** [comment]
That's the same place i ended up, but my understanding of the (huge) Compose internal type system isn't good enough to recommend the correct setup.

And you are right, it's not obvious that the svg backend has own code to render (btw: it's also possible to render svg via Compose and Cairo). The svg.jl somehow manages to get around this race condition.

**Comment by dgleich** [comment]
Actually, one fix is just to reverse the order of the properties:
