### ISSUE TITLE
Replace "ASCIIString" with "AbstractString" at Compose/src/property.jl:476

### ISSUE THREAD

**Issue by montyvesselinov** [GiovineItalia/Compose.jl#186]
Compose/src/property.jl:476

immutable SVGClassPrimitive <: PropertyPrimitive
    value::AbstractString
end

This causes Gadfly plotting problems in 0.4; they worked in 0.3

**Comment by darwindarak** [comment]
This is already in PR #183.  I'm just a little cautious about making the change to all instances of `ASCIIString`.

**Comment by montyvesselinov** [comment]
Hope this change can be made soon. Thank you very much!

**Comment by montyvesselinov** [comment]
Is this going to be addressed soon.

-monty

**Comment by darwindarak** [comment]
I just made all the replacements.  Can you checkout the PR and see if it solves the problem?  We might have to do the same thing in Gadfly.

**Comment by bjarthur** [comment]
please reopen if this is still relevant
