### ISSUE TITLE
Pkg.test() on windows with Julia-0.5 fails

### ISSUE THREAD

**Issue by mdpradeep** [GiovineItalia/Compose.jl#222]
Here's the error:

```
...
...
text.png:
Binary files C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\pkgs-0.5.0.1\v0.5\Com
pose\test\data\text.png and C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\pkgs-0
.5.0.1\v0.5\Compose\test\text.png differ



 in error(::String) at .\error.jl:21
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\pkgs-0.5.0.1\v0.5\Co
mpose\test\compare_examples.jl, in expression starting on line 37
while loading C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\pkgs-0.5.0.1\v0.5\Co
mpose\test\runtests.jl, in expression starting on line 28
===============================[ ERROR: Compose ]===============================


failed process: Process(`'C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\Julia-0.
5.0\bin\julia' -Cx86-64 '-JC:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\Julia-0
.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-co
verage=none --color=yes --compilecache=yes 'C:\Users\julia\AppData\Local\JuliaPr
o-0.5.0.1\pkgs-0.5.0.1\v0.5\Compose\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================

INFO: Removing Cairo v0.2.35
INFO: Removing Graphics v0.1.3
ERROR: Compose had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:74
0
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array
{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{Abstract
String,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{Abstra
ctString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::V
ararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::A
rray{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:25
8
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
```

**Comment by lobingera** [comment]
Mac OSX?

**Comment by lobingera** [comment]
My first assumption would be: font problems.

**Comment by shashi** [comment]
It seems there are no common fonts between Windows, Linux and OSX. There are several options here:

1. Disable text tests on all but OSX (since it passes in OSX)
2. Install the same font on all OSes, then run the tests. This is considerably harder

**Comment by lobingera** [comment]
@shashi, even doing 2 could still face problems, because the font rendering pipeline might differ. And comparing png for exact binary match might also be a problem (same content might have different representation). In Cairo testing we're using the check if the output file is available and if it has the right header. This might be too loose on rendering issues, but it's a good check if the package itself is able to produce output.

**Comment by tkelman** [comment]
Or use different reference images for different OS'es.

**Comment by lobingera** [comment]
@tkelman Our unfortunate situation already starts at the availability of a font to OS mapping... 
If we could assume, that any MAC OS installation provides a font X that renders bitexact with any rendering pipeline, we already would have a startpoint.

**Comment by tbreloff** [comment]
If you're going to spend time on this problem, could you maybe consider collaborating on https://github.com/tbreloff/VisualRegressionTests.jl?

**Comment by lobingera** [comment]
... for a bitmap only comparision this might be an option, although it looks like main comparison work is still in Images ...

**Comment by tlnagy** [comment]
This is stale at this point, tests should be working properly on `Compose` master. Please open a new issue if that's not the case.
