### ISSUE TITLE
How do I draw an arc?

### ISSUE THREAD

**Issue by NickMcNutt** [GiovineItalia/Compose.jl#227]
This is either missing from the documentation or I am unable to find how to do this.  If I want to draw an arc (that represents part of the circumference of a circle), how would I do that with Compose.jl?  Thanks!

**Comment by TravisA9** [comment]
Looking for the same!

**Comment by lobingera** [comment]
You will need to implement it. You can follow the primitives in from.jl (like rectangle or circle) and the corresponding actions in the backends.

**Comment by TravisA9** [comment]
Ok, thanks!
