### ISSUE TITLE
can't draw less than sign

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Compose.jl#235]
```
julia> using Compose

julia> img = PNG("text.png", 400px, 400px);

julia> c = compose(compose(context(), text(150px, 200px, "hello < goodbye")), fill("tomato"));

julia> draw(img, c);

(process:8593): Pango-WARNING **: pango_layout_set_markup_with_accel: Error on line 1 char 16: ' ' is not a valid character following a '<' character; it may not begin an element name
```

i suggest we revert https://github.com/GiovineItalia/Compose.jl/pull/111 and instruct users to use the `&XXX;` notation for symbols.

**Comment by tlnagy** [comment]
Is there no other way that we can resolve this?

**Comment by lobingera** [comment]
Documentation?

**Comment by bjarthur** [comment]
@lobingera by "Documentation?", are you saying that you agree we should revert, and then document the fact that HTML ampersand number/name codes need to be used for symbols?

worth noting that the "fix" in https://github.com/GiovineItalia/Compose.jl/pull/111 only works for the cairo backend, not svg, and makes it impossible to print any symbol other than ampersand.

**Comment by lobingera** [comment]
See my comment: https://github.com/GiovineItalia/Compose.jl/pull/111#issuecomment-301406187

In the first place it should be mentioned in the Documentation, that labeling is based on pango for these backends and SVG for SVG. And some examples what should work. 

I have to admit, that of all tools i work with (matlab, several plotting options in python and some very strange online tools) NOONE does a proper/understandable text markup. Maybe this is also one of the missing pieces in modern computing...
