### ISSUE TITLE
Problem with round in misc.jl on 32bit system

### ISSUE THREAD

**Issue by trohwer** [GiovineItalia/Compose.jl#242]
The a*b.value at the end of the file seems to exceed the Int32 type in some cases.

    *(a::AbstractFloat, b::Dates.Millisecond) = Dates.Millisecond(round(Integer, (a * b.value)))

After changing the type Integer to Int64, this problem disappered for me.

**Comment by tlnagy** [comment]
What cases cause this to happen?

**Comment by trohwer** [comment]
You can reproduce this with the following (on a 32bit system):

using Gadfly
using Cairo

myplot=plot(x=[Dates.DateTime(2017,4,1)+Dates.Day(i) for i=1:10],y=[i for i=1:10],Geom
draw(PDF("test.pdf", 4inch, 3inch), myplot)


ERROR: InexactError()
 in trunc(::Type{Int32}, ::Float64) at ./float.jl:458
 in * at /home/tr/.julia/v0.5/Compose/src/misc.jl:247 [inlined]
 in * at /home/tr/.julia/v0.5/Compose/src/misc.jl:248 [inlined]
 in resolve(::Measures.BoundingBox{Tuple{Measures.Length{:mm,Float64},Measures.Length{                                                                                         :mm,Float64}},Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}}}, ::Com                                                                                         pose.UnitBox{Float64,Float64,Float64,Float64}, ::Compose.IdentityTransform, ::Compose.                                                                                         UnitBox{DateTime,Float64,Base.Dates.Millisecond,Float64}) at /home/tr/.julia/v0.5/Comp                                                                                         ose/src/measure.jl:445
 in drawpart(::Compose.Image{Compose.PDFBackend}, ::Compose.Context, ::Compose.Identit                                                                                         yTransform, ::Compose.UnitBox{Float64,Float64,Float64,Float64}, ::Measures.BoundingBox                                                                                         {Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Lengt                                                                                         h{:mm,Float64},Measures.Length{:mm,Float64}}}) at /home/tr/.julia/v0.5/Compose/src/con                                                                                         tainer.jl:511
 in drawpart(::Compose.Image{Compose.PDFBackend}, ::Compose.Table, ::Compose.IdentityT                                                                                         ransform, ::Compose.UnitBox{Float64,Float64,Float64,Float64}, ::Measures.BoundingBox{T                                                                                         uple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Length{                                                                                         :mm,Float64},Measures.Length{:mm,Float64}}}) at /home/tr/.julia/v0.5/Compose/src/conta                                                                                         iner.jl:477
 in drawpart(::Compose.Image{Compose.PDFBackend}, ::Compose.Context, ::Compose.Identit                                                                                         yTransform, ::Compose.UnitBox{Float64,Float64,Float64,Float64}, ::Measures.BoundingBox                                                                                         {Tuple{Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}},Tuple{Measures.Lengt                                                                                         h{:mm,Float64},Measures.Length{:mm,Float64}}}) at /home/tr/.julia/v0.5/Compose/src/con                                                                                         tainer.jl:590 (repeats 2 times)
 in draw(::Compose.Image{Compose.PDFBackend}, ::Compose.Context) at /home/tr/.julia/v0                                                                                         .5/Compose/src/container.jl:434
 in draw(::Compose.Image{Compose.PDFBackend}, ::Gadfly.Plot) at /home/tr/.julia/v0.5/G                                                                                         adfly/src/Gadfly.jl:934

**Comment by trohwer** [comment]
The code got a bit truncated, when copy/pasting:

using Gadfly
using Cairo

myplot=plot(x=[Dates.DateTime(2017,4,1)+Dates.Day(i) for i=1:10],y=[i for i=1:10],Geom.point,Geom.smooth)
draw(PDF("test.pdf", 4inch, 3inch), myplot)
