### ISSUE TITLE
travis on each commit?

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Compose.jl#253]
if a Compose PR has multiple commits, travis is run on each separately.  this differs from Gadfly, in which travis is just run once for the whole PR.  it's not obvious to me how the small differences between the .travis.yml files for these two repos cause this difference in behavior.  it's not desired, right?  how to change it?

**Comment by tlnagy** [comment]
Not sure why the difference, but there is an option to auto-cancel builds in the Travis settings: https://travis-ci.org/GiovineItalia/Compse.jl/settings

**Comment by bjarthur** [comment]
the only difference i can see is that i've been inadvertently pushing PRs directly to GiovineItalia/Compose.jl, whereas my PRs to Gadfly have been to bjarthur/Gadfly.jl.  i've reconfigured the remote URLs on my local Compose repo to point to bjarthur/Compose.jl.  we'll see if this reduces the load on the travis servers next time i make a pull request.

**Comment by tlnagy** [comment]
I haven't found this to be a major problem since we enabled auto-cancellation of builds.
