### ISSUE TITLE
replace coveralls with codecov?

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Compose.jl#255]
Compose currently uses Coveralls to measure testing coverage, whereas Gadfly uses Codecov.  is there a reason for the difference?  i'd like to put a coverage badge in Compose's README.

**Comment by tlnagy** [comment]
Gadfly was switched over to Codecov because I found Coveralls annoying. Which ever you like better works for me. We should be consistent between the two packages though.

**Comment by bjarthur** [comment]
how do i add Compose to Codecov?  [this page](https://codecov.io/gh/GiovineItalia/Compose.jl) says i don't have permission.

**Comment by tlnagy** [comment]
I activated it. I'm surprised you don't have access since Codecov uses Github permissions. Were you logged in with your github account?

**Comment by tlnagy** [comment]
maybe the problem was that you were a member of the organization and not an owner. I upgraded your account to maximum so it should work from here on out.

**Comment by tlnagy** [comment]
This was resolved awhile ago, closing
