### ISSUE TITLE
Replace Iterators by IterTools to fix build on Julia v0.6

### ISSUE THREAD

**Issue by juliohm** [GiovineItalia/Compose.jl#260]
There is a naming issue affecting many packages on Julia v0.6. This issue led to a rename of `Iterators` to `IterTools`. Like in other packages, the workaround is to use `IterTools` instead:

https://github.com/JuliaMath/Combinatorics.jl/issues/48

Could you please fix this issue and tag a new version?

**Comment by bjarthur** [comment]
it's already fixed by https://github.com/GiovineItalia/Compose.jl/pull/259.  just checkout master until the next tag
