### ISSUE TITLE
Broken Golden Rectangle example

### ISSUE THREAD

**Issue by mbeltagy** [GiovineItalia/Compose.jl#273]
When I try to generate an SVG using 
[examples/golden_rec.jl](https://github.com/GiovineItalia/Compose.jl/blob/master/examples/golden_rect.jl)
It comes out empty. 
I am using Julia 0.6.2-pre.3 
and 
```julia
julia> Pkg.status("Compose")
 - Compose                       0.5.4+             master


```

**Comment by tlnagy** [comment]
This works on `Compose` master on Julia 1.0. Please open a new issue if you're still running into this.
