### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by nickeubank** [GiovineItalia/Compose.jl#274]
I notice Compose isn't passing 0.6 tests. Is this package still being supported?

**Comment by bjarthur** [comment]
yes, it is.  i've got a [PR](https://github.com/GiovineItalia/Compose.jl/pull/271) that fixes the tests, among other things.  why do you ask?

**Comment by nickeubank** [comment]
Oh great! Hitting some issues with a down-stream package (`GraphPlots.jl`), was curious when I say tests about whether problem was a stale dependency. Thanks!
