### ISSUE TITLE
Tagging 1.0 compatible release?

### ISSUE THREAD

**Issue by jpfairbanks** [GiovineItalia/Compose.jl#297]
We are ready to update GraphPlot.jl for julia 1.0 https://github.com/JuliaGraphs/GraphPlot.jl/pull/66. Is Compose ready to tag a 1.0 compatible release?

**Comment by zsunberg** [comment]
I'd really like to use Compose in software that will be used for a course at Stanford in the fall, but we need a 1.0 release - just wanted to give a bump to this :)

**Comment by tlnagy** [comment]
@zsunberg When do you all start? Compose master already works (can be used via `pkg"add Compose#master"` on Julia 1.0. We also just merged Julia 1.0 support into `Gadfly.jl` so if you can give it a spin and make sure everything works for you that would be great. We can tag soon.

**Comment by zsunberg** [comment]
Hi @tlnagy , we probably won't have students using it for another month, but we are trying to get prepared early so everything is smooth. I have been using master, but we just want as few hiccups as possible when a few hundred people are downloading thing, so a tag would be ideal

**Comment by tlnagy** [comment]
@zsunberg Certainly, I'm planning on tagging a new release for Compose by the end of the week and tag Gadfly shortly after.

**Comment by zsunberg** [comment]
Awesome, that looks great! Thanks @Mattriks

**Comment by tlnagy** [comment]
I've tagged a new release, now just waiting for it to merge https://github.com/JuliaLang/METADATA.jl/pull/18426. Let us know if you all run into bugs or difficulties with the new release.

**Comment by tlnagy** [comment]
Compose v0.7.0 with support for Julia 1.0 is now out.

**Comment by zsunberg** [comment]
Woohoo! Thanks @tlnagy

**Comment by simonschoelly** [comment]
GraphPlot works, thank you very much @tlnagy
