### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by davidanthoff** [GiovineItalia/Compose.jl#330]
Would be great to get a release that has https://github.com/GiovineItalia/Compose.jl/pull/327 in it.

**Comment by bjarthur** [comment]
yep, i've been thinking we should tag soon too.  a few issues to consider beforehand:

https://github.com/GiovineItalia/Compose.jl/pull/324
https://github.com/GiovineItalia/Compose.jl/issues/322
https://github.com/GiovineItalia/Gadfly.jl/issues/1226

**Comment by Mattriks** [comment]
GiovineItalia/Gadfly.jl#1226 is a Gadfly issue. Did you mean GiovineItalia/Gadfly.jl#1225? Multiline text for svg is an issue that needs fixing in Compose.

**Comment by bjarthur** [comment]
https://github.com/GiovineItalia/Gadfly.jl/issues/1226 concerns opacity, and might hence be related to #324 and #322.  are these latter two issues resolved and just not closed?  if so, i'm fine with tagging now.  multi-line text is a newish issue that can wait to be included in another release.

@tlnagy thoughts?

**Comment by Mattriks** [comment]
Gadfly has never supported opacity in the `color` aesthetic (and hence not in the color key), e.g. GiovineItalia/Gadfly.jl#844. It can be done for `Geom.ribbon`  and `Geom.polygon` via `Theme(lowlight_color=opacity function)`, but I see that as a temporary patch, and opacity in the `color` aesthetic really needs a well thought out design in Gadfly.

**Comment by bjarthur** [comment]
plan is to tag a release tomorrow after i test out the latest merges to master today.  please let me know if there are any problems with the current master branch.

**Comment by bjarthur** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/19871
