### ISSUE TITLE
Tag a new version? 

### ISSUE THREAD

**Issue by dourouc05** [GiovineItalia/Compose.jl#364]
I'm having troubles with many packages using DataStructures, the problem being that the latest tagged version of Compose.jl is limited to DataStructures 0.15, while master goes up to 0.17. Would it be possible to tag a new version of this package, with the updated requirements? 

(For now, I'm following master as a temporary workaround.)

**Comment by epatters** [comment]
Seconding this request. Also, if Compose does not depend on the specific version of DataStructures, maybe the version requirement should be liberalized to something like `^0.11` and likewise for the other dependencies?

**Comment by tlnagy** [comment]
We've already discussed relaxing the dependencies here: https://github.com/GiovineItalia/Gadfly.jl/issues/1287. We decided to restrict the dependencies and rely on CompatHelper to upgrade them when new version come out. I think that @non-Jedi's argument swayed us https://github.com/GiovineItalia/Gadfly.jl/pull/1283#issuecomment-489631263

That said that strategy, if done properly, would involve us pushing more frequent patch releases, which we haven't done.

**Comment by tlnagy** [comment]
There seems to be complicated dependency resolution issues I'm running into attempting to tag Compose while using Gadfly 1.1.0. I'm attempting to resolve now, but it's likely that we'll need to coordinate a tag with Gadfly as well to make this work. Thoughts @bjarthur and @Mattriks?

**Comment by tlnagy** [comment]
I can confirm that all Gadfly v1.1.0 tests pass in a new environment using Compose master so this could work as a patch release. However, we're also dropping support for Julia v0.7 in this cycle so we'll need to make this a minor release, ref faa33ff792649cbfdc046443368065df6b35e8dc

**Comment by tlnagy** [comment]
Compose v0.8.0 is now out.
