### ISSUE TITLE
compats

### ISSUE THREAD

**Issue by Mattriks** [GiovineItalia/Compose.jl#374]
- Colors 0.11
- Cairo 1.0

**Comment by Mattriks** [comment]
I think Cairo.jl 1.0 was tagged before CompatHelper was installed here, hence CompatHelper doesn't pick it up?

**Comment by bjarthur** [comment]
maybe becuase Cairo is in "extras", not a "deps".

**Comment by tlnagy** [comment]
I realized we were missing the Colors v0.11 dep in v0.8.0 when I pushed it out. If someone wants to manually push the Cairo change then we can make a patch release to bump Compose.
