### ISSUE TITLE
Package Compose does not have Cairo in its dependencies

### ISSUE THREAD

**Issue by jonathanBieler** [GiovineItalia/Compose.jl#378]
I'm trying to register a new release of Immerse in General (using a Project.toml file instead REQUIRE), the tests pass on travis, but fails when trying to register :

https://github.com/JuliaRegistries/General/pull/7475/checks?check_run_id=372516387#step:5:917

```julia 
[ Info: Successfully `Pkg.add`ed package
[ Info: Attempting to `import` package
WARNING: eval into closed module Compose:
Expr(:block, #= Symbol("/tmp/jl_08l8ER/packages/Immerse/p0IT8/src/Immerse.jl"):11 =#, Expr(:import, Expr(:., :Cairo)))
  ** incremental compilation may be fatally broken for this module **

ERROR: LoadError: ArgumentError: Package Compose does not have Cairo in its dependencies:
- If you have Compose checked out for development and have
  added Cairo as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Compose
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:900
 [2] top-level scope at /tmp/jl_08l8ER/packages/Immerse/p0IT8/src/Immerse.jl:11
 [3] eval(::Module, ::Any) at ./boot.jl:330
 [4] top-level scope at /tmp/jl_08l8ER/packages/Immerse/p0IT8/src/Immerse.jl:11
 [5] include at ./boot.jl:328 [inlined]
```

Is there a way to fix that on my side ? It seems it's just complaining about Compose. That's my Project.toml :

https://github.com/JuliaGraphics/Immerse.jl/blob/master/Project.toml#L22

**Comment by tlnagy** [comment]
Why do you have Cairo pinned at v1.0 in your `Project.toml`? There might be some weird behavior where you are forcing Cairo v1.0, which isn't guaranteed to be compatible with Compose stable. I see that you tagged Compose at v0.7.3, which is the last release where we were super-lax with our version compatibility. Am I right for assuming that you pinned Compose at that version since the later ones (v0.7.4 and v0.8.0) failed locally?

**Comment by jonathanBieler** [comment]
I'm using v1.0 Cairo since it's first version that use the new artifact system for binary dependency. I'm not sure about Compose, I think I put the one I had on my machine (and worked).

But the issue is that Compose doesn't have Cairo in its dependency, so it fails at the package manager level, before anything gets installed. On the repository it throws only a warning, but General consider it as an error, not sure why.

https://travis-ci.org/JuliaGraphics/Immerse.jl/jobs/632313868#L151

**Comment by Mattriks** [comment]
Here's a compatibility table for Compose and Cairo:

| Compose.jl | Cairo.jl |
|----------|----------|
| 0.7.x | 0.5, 0.6 | 
| 0.8 | 0.7, 0.8 |
| master | 0.7, 0.8, 1.0 |

A brief history is that the names of the Cairo libraries that julia calls changed in Cairo.jl 0.7, and then Cairo.jl switched to using Artifacts in Cairo.jl 1.0.

**Comment by jonathanBieler** [comment]
It got merged manually, it seems to be one of these issue with optional dependencies.
