### ISSUE TITLE
Adding support for Colors.jl v0.10

### ISSUE THREAD

**Issue by kimikage** [GiovineItalia/Compose.jl#380]
I am currently working on making Gadfly.jl compatible with Colors.jl v0.11 (and v0.10).
(cf. https://github.com/GiovineItalia/Gadfly.jl/issues/1368, https://github.com/GiovineItalia/Gadfly.jl/pull/1369)

There is no reason to exclude Colors v0.10 from the [compat] entry, since the compatibility with Colors.jl in Gadfly.jl is capped at v0.9.
https://github.com/GiovineItalia/Gadfly.jl/blob/bf50828f8603ab0b4f918b5247d9c99186960876/Project.toml#L31-L34

In fact, the current master (https://github.com/GiovineItalia/Compose.jl/commit/20485b11a134cebf81897e374cdf4678ff657c22) seems to be compatible with Colors.jl v0.10
https://travis-ci.org/kimikage/Compose.jl/builds/633591993

Of course, since Colors.jl v0.11 is already supported, adding support for Colors.jl v0.10 has little benefit for end users. So, this is just a matter of making the dependencies reasonable.

**Comment by Mattriks** [comment]
Is the use of color names in Colors v0.10, consistent with the use of color names in Colors v0.9.x and Colors v0.11?  Even if Compose passes testing with Colors v0.10, are there are there other reasons that we might not want to support it?

**Comment by kimikage** [comment]
### use of color names
- Colors v0.9.6 vs Colors v0.10.1
  - There are breaking changes. (https://github.com/JuliaGraphics/Colors.jl/pull/360, https://github.com/JuliaGraphics/Colors.jl/pull/390)
  - The changes do not affect the code in Compose.jl itself.
  - The end users and downstream packages have the choice to use Colors v0.9.6 *for now*. (Perhaps other packages will abandon Colors v0.9, though.)
- Colors v0.10.1 vs Colors v0.11.1 or later
  - There is no change in the use of color names.

### other reasons that we might not want to support it
- The downstream packages need to be checked for the compatibility with Colors v0.10.
  - However, I don't think it is a problem for *higher-level* packages like Compose.jl.
- Colors v0.1x, not just v0.10, are the preparations to release Colors v1.0 and probably have a short support period.

**Comment by bjarthur** [comment]
@Mattriks are you arguing that we should *not* add Colors 0.10 to Compose?  my shallow understanding is that it is just a change in the permitted color names, and if Compose does not use them directly, but just passes them through from the user, then we should permit that.

**Comment by kimikage** [comment]
In addition, there are actually many differences between v0.9.6 and v0.10, other than color names.

However, the important thing is that v0.10 and v0.11 are functionally identical. The difference is the renames of the rarely used types, `RGB1` and `RGB4`.

**Comment by Mattriks** [comment]
@bjarthur We need to add a link to the  Compose and Gadfly docs about the allowed color names:
http://juliagraphics.github.io/Colors.jl/latest/namedcolors/

**Comment by ben-schulz** [comment]
submitted a relevant pull request in response to issue #1374;

sorry, meant to reference this issue instead, as @bjarthur originally requested
