### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by Mattriks** [GiovineItalia/Compose.jl#384]
Currently Compose does not handle the `Missing` type.  But the basis of Compose is `Measure` units, so all numbers are converted to `Measure` units anyway, including NaNs (either natively supported by Compose's graphical backends or already handled in Compose).
This means that there is a simple fix to supporting the `Missing` type in Compose:
```julia
Compose.x_measure(a::Missing) = Compose.x_measure(NaN)
Compose.y_measure(a::Missing) = Compose.y_measure(NaN)

y = [rand(5); missing; rand(4)]
points = collect(Tuple, zip(1:10, y))
compose(context(units=UnitBox(0,0, 10, 1)), line([points]), stroke("black") )
```
![Missing](https://user-images.githubusercontent.com/18226881/73510932-fa36b200-4437-11ea-89a0-41b76bce52ff.png)

This fix would pave the way for supporting Missing values in Gadfly, because it means that Compose won't error when it comes to drawing the plot. 

Comments?  If none, I'll open a PR here sometime.

**Comment by bjarthur** [comment]
seems reasonable.  let's do it!

**Comment by Mattriks** [comment]
I'll also work on fixing some other problems in Compose. The next example works for PNG, but for SVG the black line gets truncated, and the red line doesn't appear.

```julia
x = 1:8
p1 = collect(Tuple, zip(x, [rand(2); NaN; 0.4; NaN; rand(3)]))
p2 = collect(Tuple, zip(x, [NaN; rand(7)]))

p = compose(context(units=UnitBox(0,0, 10, 1)), 
    (context(), rectangle(), fill(nothing), stroke("gray")),
    (context(), line([p1]), stroke("black")),
    (context(), line([p2]), stroke("red"))  
)
draw(SVG(), p) # problems 
draw(PNG(), p)
```
![iss1391](https://user-images.githubusercontent.com/18226881/73616820-466a3800-466c-11ea-93b6-6fe4da11e012.png)
