### ISSUE TITLE
Rectangle rotation doesn't work

### ISSUE THREAD

**Issue by isopteryx** [GiovineItalia/Compose.jl#436]
The following doesn't rotate a rectangle, just shifts it a bit:

```julia
compose(
    context(rotation=Rotation(π/3)),
    rectangle(0.2w, 0.2h, 0.6w, 0.6h),
    fill(colorant"orange"))
```

For ellipse the same code produces an expected result.

Julia version 1.6.0, Compose v0.9.2.

**Comment by Mattriks** [comment]
Yes there was PR #338, but it ran into issues (to be resolved!)

**Comment by isopteryx** [comment]
Thank you, sorry for duplicate.

**Comment by isopteryx** [comment]
I followed the #338, and now just use `polygon` with 4 points instead.
