### ISSUE TITLE
circle() example broken

### ISSUE THREAD

**Issue by mmayo888** [GiovineItalia/Compose.jl#93]
Hi, the third example on the documentation page here at composejl.org appears to be broken.

The following commands:

using Compose
comp=compose(context(),
        (context(), circle(), fill("bisque")),
        (context(), rectangle(), fill("tomato")))

lead to the following error:

ERROR: `circle` has no method matching circle()

The example can be fixed by specifying that the call to circle() is from the Compose package:

comp=compose(context(),
        (context(), Compose.circle(), fill("bisque")),
        (context(), rectangle(), fill("tomato")))

I'm using Julia 0.3.3 on Mac OS 10.10.1.

**Comment by bjarthur** [comment]
works for me using julia 0.6 and compose master.  closing since this is so old.  please reopen if still relevant.
